### ISSUE TITLE
[UX] Typo in README

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/testimonial_recipe#2]
![image](https://user-images.githubusercontent.com/1705388/142276672-7ce66ef3-6af3-44b2-b27e-bd82b5d149e2.png)

Change hyphen for underscore...  

https://github.com/backdrop-contrib/testimonial_recipe/issues

**Comment by stpaultim** [comment]
Fixed! Thanks for reporting @albanycomputers
